# Site settings
title: 胜言的博客
SEOTitle: 胜言的博客 | ShengYan Blog
header-img: img/home-bg.jpg
email: 960064995@qq.com
description: "所有美好的东西都是免费的，比如阳光、空气和水。"
keyword: "BY, BY Blog, 胜言的博客, shengyan, 胜言, python, C"
url: "shengyan-coder.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Shengyan-Coder/Shengyan-Coder.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "读书好，好读书，读好书。"
sidebar-avatar: /img/avatar_m.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     6745715152
zhihu_username:     yao-long-57-48
github_username:    Shengyan-Coder
# facebook_username:  baiying.qiu.7
jianshu_username:   77a0e61753f1
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: '68570f351a151a852cc3'                            #生成的clientID
  clientSecret: '87c12bf146d6d6805af65b57293c1be1cd4f1c62'    #生成的clientSecret
  repo: 'Shengyan-Coder.github.io'    #仓库名称
  owner: 'Shengyan-Coder'    #github用户名
  admin: ['Shengyan-Coder']
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b1fe570063086117452e53d4dd2a62dd

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "网站·学习日志",
        href: "http://wsheng-note.herokuapp.com"
    },{
        title: "简书·胜言",
        href: "http://www.jianshu.com/u/77a0e61753f1"
    },{
        title: "苹果",
        href: "https://apple.com"
    }
]
